version: '3.8'
services:
  backend:
    build: 
      context: ./backend

  frontend:
    build: 
      context: ./frontend
      args:
        NODE_ENV: ${NODE_ENV-production}
        REACT_APP_USERS_SERVICE_URL: ${REACT_APP_USERS_SERVICE_URL}
        PUBLIC_URL: ${PUBLIC_URL}
        GOOGLE_RECAPTCHA_KEY: ${GOOGLE_RECAPTCHA_KEY}
        GOOGLE_RECAPTCHA_SECRET: ${GOOGLE_RECAPTCHA_SECRET}
        REACT_APP_WOO_URL: ${REACT_APP_WOO_URL}
