version: '3.8'
services:
  proxy:
    environment:
      - CF_API_EMAIL=$CLOUDFLARE_EMAIL
      - CF_API_KEY=$CLOUDFLARE_API_KEY
      - DOMAIN=${DOMAIN}

  backend:
    environment:
      - ENV=${ENV}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET=${S3_SECRET}
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PRODUCTION=1

  worker:
    environment:
      - ENV=${ENV}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET=${S3_SECRET}
      - PYTHONUNBUFFERED=1
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PRODUCTION=1

  frontend:
    environment:
      - NODE_ENV=${NODE_ENV}
      - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
      - PUBLIC_URL=${PUBLIC_URL}

  db:
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
