version: '3.8'
services:
  backend:
    build:
      context: ./backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.local
      args:
        FRONTEND_ENV: development
        NODE_ENV: development
        REACT_APP_USERS_SERVICE_URL: ${REACT_APP_USERS_SERVICE_URL}
        PUBLIC_URL: ${PUBLIC_URL}
        GOOGLE_RECAPTCHA_KEY: ${GOOGLE_RECAPTCHA_KEY}
        GOOGLE_RECAPTCHA_SECRET: ${GOOGLE_RECAPTCHA_SECRET}
        REACT_APP_WOO_URL: ${REACT_APP_WOO_URL}
    environment:
      - CHOKIDAR_USEPOLLING=true

  db:
    image: postgres:15-alpine

  adminer:
    image: adminer

  redis:
    image: redis

  proxy:
    image: traefik:chevrotin

  worker:
    image: robotlab-backend
