import enum

LIST_ATTR = [
    "total_net_profit",
    "gross_profit",
    "gross_loss",
    "commission",
    "profit_factor",
    "max_drawdown",
    "sharpe_ratio",
    "sortino_ratio",
    "ulcer_index",
    "r_squared",
    "probability",
    "total_of_trades",
    "percent_profitable",
    "winning_trades",
    "losing_trades",
    "even_trades",
    "total_slippage",
    "avg_trade",
    "avg_winning_trade",
    "avg_losing_trade",
    "ratio_win_loss",
    "max_consec_winners",
    "max_consec_losers",
    "largest_winning_trade",
    "largest_losing_trade",
    "avg_trades_per_day",
    "avg_trades_per_quarter",
    "avg_time_in_market",
    "avg_bars_in_trade",
    "profit_per_month",
    "max_time_to_recover",
    "longest_flat_period",
    "avg_mae",
    "avg_mfe",
    "avg_etd",
]

SUM_ATTR = [
    "total_net_profit",
    "gross_profit",
    "gross_loss",
    "commission",
    "profit_per_month"
]

AVG_ATTR = [
    'profit_factor',
    "max_drawdown",
    "sortino_ratio",
    'sharpe_ratio',
    # 'ulcer_index',
    'r_squared',
    # 'probability',
    'percent_profitable',
    "avg_trade",
    "avg_winning_trade",
    "avg_losing_trade",
    "ratio_win_loss",
    "largest_winning_trade",
    "largest_losing_trade",
    "avg_trades_per_day",
    "avg_time_in_market",
    "avg_bars_in_trade",
    "max_time_to_recover",
    "longest_flat_period",
    "avg_mae",
    "avg_mfe",
    "avg_etd",
]

NAME_MAPPING = {
    "total_net_profit": "Total net profit",
    "gross_profit": "Gross profit",
    "gross_loss": "Gross loss",
    "commission": "Commission",
    "profit_factor": "Profit factor",
    "profit_per_month": "Profit per month",
    "profit_per_quarter": "Profit per quarter",
    "max_drawdown": "Max. drawdown",
    "sharpe_ratio": "Sharpe ratio",
    "sortino_ratio": "Sortino ratio",
    # "ulcer_index": "Ulcer index",
    "r_squared": "R squared",
    # "probability": "Probability",
    "total_of_trades": "Total # of trades",
    "percent_profitable": "Percent profitable",
    "winning_trades": "# of winning trades",
    "losing_trades": "# of losing trades",
    "even_trades": "# of even trades",
    # "total_slippage": "Total slippage",
    "avg_trade": "Avg. trade",
    "avg_winning_trade": "Avg. winning trade",
    "avg_losing_trade": "Avg. losing trade",
    "ratio_win_loss": "Ratio avg. win / avg. loss",
    "max_consec_winners": "Max. consec. winners",
    "max_consec_losers": "Max. consec. losers",
    "largest_winning_trade": "Largest winning trade",
    "largest_losing_trade": "Largest losing trade",
    "avg_trades_per_day": "Avg. # of trades per day",
    "avg_time_in_market": "Avg. time in market",
    "max_time_to_recover": "Max. time to recover",
    "longest_flat_period": "Longest flat period",
    "avg_mae": "Avg. MAE",
    "avg_mfe": "Avg. MFE",
    "avg_etd": "Avg. ETD",
    "avg_trades_per_quarter": "Avg. # Trades / Quarter",
}

ROW_MAPPING = {
    "Total net profit": "total_net_profit",
    "Gross profit": "gross_profit",
    "Gross loss": "gross_loss",
    "Commission": "commission",
    "Profit factor": "profit_factor",
    "Profit per month": "profit_per_month",
    "Max. drawdown": "max_drawdown",
    "Sharpe ratio": "sharpe_ratio",
    "Sortino ratio": "sortino_ratio",
    "Ulcer index": "ulcer_index",
    "Probability": "probability",
    "R squared": "r_squared",
    "Total # of trades": "total_of_trades",
    "Percent profitable": "percent_profitable",
    "# of winning trades": "winning_trades",
    "# of losing trades": "losing_trades",
    "# of even trades": "even_trades",
    "Total slippage": "total_slippage",
    "Avg. trade": "avg_trade",
    "Avg. winning trade": "avg_winning_trade",
    "Avg. losing trade": "avg_losing_trade",
    "Ratio avg. win / avg. loss": "ratio_win_loss",
    "Max. consec. winners": "max_consec_winners",
    "Max. consec. losers": "max_consec_losers",
    "Largest winning trade": "largest_winning_trade",
    "Largest losing trade": "largest_losing_trade",
    "Avg. # of trades per day": "avg_trades_per_day",
    "Avg. # Trades / Quarter": "avg_trades_per_quarter",
    "Avg. time in market": "avg_time_in_market",
    "Avg. bars in trade": "avg_bars_in_trade",
    "Max. time to recover": "max_time_to_recover",
    "Longest flat period": "longest_flat_period",
    "Avg. MAE": "avg_mae",
    "Avg. MFE": "avg_mfe",
    "Avg. ETD": "avg_etd"
}

NOT_CALCULATED = [
    'Probability',
    'Longest flat period',
    'Ulcer index',
    'Total slippage'
]

NOT_CALCULATED_PROP = {
    'Probability': 'probability',
    'Longest flat period': 'longest_flat_period',
    'Ulcer index': 'ulcer_index',
    "Total slippage": "total_slippage"
}

NOT_CALCULATED_ATT = [
    'probability',
    'longest_flat_period',
    'ulcer_index',
    "total_slippage"
]

COMMISSION_LEVELS = [
    {"name": "ES", "long_name": "E-Mini S&P 500", "1": "4.20", "2": "8.00", "3": "15.00"},
    {"name": "MES", "long_name": "Micro S&P 500", "1": "1.25", "2": "2.00", "3": "4.00"},
    {"name": "NQ", "long_name": "E-Mini NASDAQ 100", "1": "4.20", "2": "8.00", "3": "15.00"},
    {"name": "MNQ", "long_name": "Micro NASDAQ 100", "1": "1.25", "2": "2.00", "3": "4.00"},
    {"name": "YM", "long_name": "E-Mini Dow Jones", "1": "4.20", "2": "8.00", "3": "15.00"},
    {"name": "MYM", "long_name": "Micro Dow Jones", "1": "1.25", "2": "2.00", "3": "4.00"},
    {"name": "RTY", "long_name": "E-Mini Russell 2000", "1": "4.20", "2": "8.00", "3": "15.00"},
    {"name": "MYM", "long_name": "Micro Russell 2000", "1": "1.25", "2": "2.00", "3": "4.00"},
    {"name": "FDAX", "long_name": "Dax Futures", "1": "4.20", "2": "8.00", "3": "15.00"},
    {"name": "GC", "long_name": "Gold Futures", "1": "4.75", "2": "9.00", "3": "16.00"},
    {"name": "MGC", "long_name": "Micro Gold Futures", "1": "1.60", "2": "3.00", "3": "6.00"},
    {"name": "SI", "long_name": "Silver Futures", "1": "4.75", "2": "9.00", "3": "16.00"},
    {"name": "HG", "long_name": "Copper Futures", "1": "4.75", "2": "9.00", "3": "16.00"},
    {"name": "CL", "long_name": "Crude Oil Futures", "1": "4.50", "2": "8.50", "3": "16.00"},
    {"name": "MCL", "long_name": "Micro Crude Oil Futures", "1": "1.60", "2": "3.00", "3": "6.00"},
    {"name": "B", "long_name": "Brent Crude Oil Futures", "1": "5.00", "2": "10.00", "3": "17.00"},
    {"name": "HO", "long_name": "Crude Oil Futures", "1": "4.50", "2": "8.50", "3": "16.00"},
    {"name": "NG", "long_name": "Natural Gas Futures", "1": "4.50", "2": "8.50", "3": "16.00"},
    {"name": "ZB", "long_name": "30 Year U.S. Treasury Bond", "1": "3.40", "2": "7.00", "3": "14.00"},
    {"name": "DX", "long_name": "Dollar Index", "1": "4.20", "2": "8.00", "3": "15.00"},
    {"name": "6A", "long_name": "Australian Dollar Futures", "1": "4.80", "2": "9.00", "3": "18.00"},
    {"name": "M6A", "long_name": "Micro Australian Dollar Futures", "1": "1.25", "2": "2.00", "3": "4.00"},
    {"name": "6B", "long_name": "British Pound Futures", "1": "4.80", "2": "9.00", "3": "18.00"},
    {"name": "M6A", "long_name": "Micro British Pound Futures", "1": "1.25", "2": "2.00", "3": "4.00"},
    {"name": "6E", "long_name": "Euro FX Futures", "1": "4.80", "2": "9.00", "3": "18.00"},
    {"name": "M6E", "long_name": "Micro Euro FX Futures", "1": "1.25", "2": "2.00", "3": "4.00"},
    {"name": "6J", "long_name": "Japanese Yen Futures", "1": "4.80", "2": "9.00", "3": "18.00"},
    {"name": "M6J", "long_name": "Micro Japanese Yen Futures", "1": "1.25", "2": "2.00", "3": "4.00"},
    {"name": "BTC", "long_name": "Bitcoin Futures", "1": "7.00", "2": "15.00", "3": "22.00"},
    {"name": "MBT", "long_name": "Micro Bitcoin Futures", "1": "4.50", "2": "8.50", "3": "16.00"},
    {"name": "CC", "long_name": "Cocoa Futures", "1": "5.20", "2": "10.00", "3": "17.00"},
    {"name": "KC", "long_name": "Coffee Futures", "1": "5.20", "2": "10.00", "3": "17.00"},
    {"name": "LE", "long_name": "Live Cattle Futures", "1": "5.20", "2": "10.00", "3": "17.00"},
    {"name": "SB", "long_name": "Sugar #11", "1": "5.20", "2": "10.00", "3": "17.00"},
    {"name": "ZC", "long_name": "Corn Futures", "1": "5.20", "2": "10.00", "3": "17.00"},
    {"name": "ZS", "long_name": "Soybean Futures", "1": "5.20", "2": "10.00", "3": "17.00"},
    {"name": "ZW", "long_name": "Wheat Futures", "1": "5.20", "2": "10.00", "3": "17.00"},
]

PORT_BOT_2 = [
    401101,
    401104,
    401105,
    401106,
    401107,
    401113,
    401114,
]

BOT_NAMES = [
    "After Party",
    "Average Joe Cool",
    "Back To The Futures",
    "Break Dancer",
    "Brunch Ranger",
    "Breakout Unicorn",
    "Chaos Theory",
    "Countertrend Majestro",
    "Early Birdie",
    "Energizer bunny",
    "Eternal Edge",
    "Golden Parachute",
    "Iron Man",
    "Low Volatility Rider",
    "Meme Squeezer",
    "Midas Touch",
    "Mother Gusher",
    "Natural Einstein",
    "Profit Sniper",
    "Pullback Artist",
    "Sigmund Freud",
    "Sleeper Cell",
    "Spike",
    "Straight No Chaser",
    "Trend Stalker",
    "Wild Catter",
]

ENABLE_BOTS = [
    "After Party",
    "Average Joe Cool",
    "Back To The Futures",
    "Break Dancer",
    "Breakout Unicorn",
    "Brunch Ranger",
    "Chaos Theory",
    "Countertrend Majestro",
    # "DT30",
    # "DT31",
    # "DT32",
    "Early Birdie",
    "Energizer Bunny",
    "Equalizer",
    "Eternal Edge",
    "Golden Parachute",
    "Iron Man",
    "Low Volatility Rider",
    "Meme Squeezer",
    "Midas Touch",
    "Mother Gusher",
    "Natural Einstein",
    "Profit Sniper",
    "Pullback Artist",
    "Sigmund Freud",
    "Sleeper Cell",
    "Spike",
    "Steady Eddy",
    "Straight No Chaser",
    "Tech Titan",
    "Trend Stalker",
    "Wild Catter",
]

ROBOT_MARKET_TAG = {
    'Sigmund Freud': 'Gold & Micro Gold Futures',
    'Iron Man': 'Gold & Micro Gold Futures',
    'Natural Einstein': 'Natural Gas Futures',
    'Energizer Bunny': 'Natural Gas Futures',
    'Wild Catter': 'Crude Oil & Micro Crude Oil Futures',
    'Mother Gusher': 'Crude Oil & Micro Crude Oil Futures',
}

active = ['401101', '401102', '401104', '401105', '401109', '401114']
ambitious = ['401103', '401106', '401107', '401108', '401111', '401115']
aggressive = ['401110', '401112', '401113']

GROUP_MAP = [
    # 'active',
    'ambitious',
    'aggressive',
]

TYPE_MAP = [
    'single_robots',
    'portfolios',
    'addon_packs',
]

ROBOT_TAG = 'single_robots'
PORT_TAG = 'portfolios'
ADDON_TAG = 'addon_packs'

BACKTEST_TYPE_COMMISSION = {
    "ES": [2, 4],
    "MES": [51, 102],
    "NQ": [2, 4],
    "MNQ": [51, 102],
    "CL": [2.26, 4.52],
    "NG": [2.26, 4.52],
    "GC": [2.31, 4.62],
    "MGC": [0.76, 1.52]
}

DATETIME_FORMAT = [
    'MM/DD/YYYY',
    'YYYY-MM-DD',
    'MM-DD-YYYY'
]

TRADE_MAP = {
    'Trade number': "number",
    'Account': "account",
    'Instrument': 'instrument',
    'Strategy': 'signal_name',
    'Market pos.': 'market_pos',
    'Qty': "quantity",
    'Entry price': "entry_price",
    'Exit price': "exit_price",
    'Entry time': "entry_time",
    'Exit time': "exit_time",
    'Entry name': 'entry_name',
    'Exit name': 'exit_name',
    'Profit': "profit",
    'Cum. net profit': "cum_net_profit",
    'Commission': "commission",
    'MAE': "mae",
    'MFE': "mfe",
    'ETD': "etd",
    'Bars': "bars",
}

LONG = 'Long'
SHORT = 'Short'

ALL_TRADE = 'All trades'
SHORT_TRADE = 'Short trades'
LONG_TRADE = 'Long trades'

LIST_TRADE = [
    ALL_TRADE,
    SHORT_TRADE,
    LONG_TRADE
]

ES = 'ES'
MES = 'MES'
ROBOT_TYPE = [ES, MES]

ALL = 'All'
WP_CACHE_KEY = 'WP_TOKEN'

CRM_TO_STL_MAP = {
    'mae_currency': 'mae',
    'mfe_currency': 'mfe',
    'profit_currency': 'profit'
}

POINT_VALUE_MAP = {
    '6A': 100000,
    '6B': 62500,
    '6C': 100000,
    '6E': 125000,
    '6J': 12500000,
    '6S': 125000,
    'B': 40,
    'CL': 1000.0,
    'E7': 62500,
    'ES': 50.0,
    'GC': 100.0,
    'GE': 2500,
    'GF': 500,
    'HE': 400,
    'HG': 25000.0,
    'LE': 400,
    'M2K': 5.0,
    'MCL': 100.0,
    'MES': 5.0,
    'MGC': 10.0,
    'MNQ': 2.0,
    'MYM': 0.5,
    'NG': 10000.0,
    'NKD': 5.0,
    'NQ': 20.0,
    'QG': 2500.0,
    'QM': 500.0,
    'RB': 21,
    'RTY': 50.0,
    'SI': 5000,
    'TN': 1000,
    'UB': 1000,
    'YM': 5.0,
    'ZB': 1000,
    'ZC': 50,
    'ZF': 1000,
    'ZL': 600,
    'ZM': 100,
    'ZN': 1000,
    'ZS': 50,
    'ZT': 2000
}

EDGE_RATIO = {
    "180100": 1.54,
    "180101": 1.42,
    "180102": 6.98,
    "180103": 12.43,
    "180104": 1.09,
    "180105": 1.15,
    "180106": 1.53,
    "180107": 19.22,
    "180108": 1.87,
    "180109": 2.46,
    "180110": 5,
    "180111": 17.19,
    "180112": 1.79,
    "180113": 1.29,
    "180114": 5.26,
    "180115": 2.1,
    "180116": 1.44,
    "180117": 1.54,
}

ROBOT_MARKETS = {
    "180100": "CL / MCL",
    "180101": "CL / MCL",
    "180102": "ES / MES",
    "180103": "ES / MES",
    "180104": "ES / MES",
    "180105": "ES / MES",
    "180106": "GC / MGC",
    "180107": "GC / MGC",
    "180108": "GC / MGC",
    "180109": "NQ / MNQ",
    "180110": "GC / MGC",
    "180111": "CL / MCL",
    "180112": "YM/MYM",
    "180113": "YM/MYM",
    "180114": "YM/MYM",
    "180115": "YM/MYM",
    "180116": "YM/MYM",
    "180117": "ZB",
}

MARKET_LONG_NAME_MAP = {
    '6A': 'Australian Dollar',
    'M6A': 'Australian Dollar & Micros',
    '6B': 'British Pound',
    'M6B': 'British Pound & Micros',
    '6E': 'Australian Dollar Futures',
    'M6E': 'Australian Dollar Futures & Micro',
    '6J': 'Japanese Yen Futures',
    'B': 'Brent Crude Oil Futures',
    'CC': 'Cocoa Futures',
    'CL': 'Crude Oil',
    'MCL': 'Crude Oil & Micros',
    'ES': 'E-Mini S&P 500',
    'MES': 'E-Mini S&P 500 & Micros',
    'FDAX': 'DAX Futures',
    'FDXS': 'DAX Futures & Micro',
    'GBTC': 'GrayScale Bitcoin Trust (Bitcoin)',
    'GC': 'Gold Futures',
    'MGC': 'Gold Futures & Micros',
    'HO': 'Heating Oil (NY Harbor ULSD) Futures',
    'LE': 'Live Cattle Futures',
    'NG': 'Henry Hub Natural Gas Futures',
    'NQ': 'E-Mini NASDAQ-100',
    'MNQ': 'E-Mini NASDAQ-100 & Micros',
    'RTY': 'E-Mini Russell 2000',
    'M2K': 'E-Mini Russell 2000 & Micros',
    'SI': 'Silver Futures',
    'YM': 'E-Mini Dow',
    'MYM': 'E-Mini Dow & Micros',
    'ZB': 'U.S. Treasury Bond Futures',
    'ZC': 'Corn Futures',
    'ZS': 'Soybean Futures'
}

MICRO = 'micro'
REGULAR = 'regular'

TYPE_MULTIPLE = {
    REGULAR: 1,
    MICRO: 0.1
}

MICRO_MARKET = [
    "M2K",
    "MES",
    "MNQ",
    "MCL",
    "MYM",
]

REGULAR_MARKET = [
    '6A',
    '6B',
    '6C',
    '6E',
    '6J',
    '6S',
    'CC',
    'E7',
    'ES',
    'GE',
    'GF',
    'HE',
    'LE',
    'NKD',
    'NQ',
    'RTY',
    'CL',
    'NG',
    'QG',
    'QM',
    'GC',
    'HG',
    "HO",
    'SI',
    'TN',
    'UB',
    'YM',
    'ZB',
    'ZC',
    'ZF',
    'ZL',
    'ZM',
    'ZN',
    'ZS',
    'ZT',
    'FDAX',
    "GBTC"
]

NORMAL = "normal"
PRO = "pro"

GROUP_CHOICES = (
    ("Normal", NORMAL),
    ("Pro", PRO),
)

COMMISSION_LEVEL = {
    "ES": {1: 4.20, 2: 8.00, 3: 15.00},
    "MES": {1: 1.25, 2: 2.00, 3: 4.00},
    "NQ": {1: 4.20, 2: 8.00, 3: 15.00},
    "MNQ": {1: 1.25, 2: 2.00, 3: 4.00},
    "YM": {1: 4.20, 2: 8.00, 3: 15.00},
    "MYM": {1: 1.25, 2: 2.00, 3: 4.00},
}

DEFAULT_COMMISSION_VALUE = {1: 1.25, 2: 2.00, 3: 4.00}


class Commission(enum.Enum):
    LOW = 1
    MID = 2
    HIGH = 3


MICRO_MAP = {
    '6A': 'M6A',
    '6B': 'M6B',
    '6E': 'M6E',
    '6J': '',
    'B': '',
    'CC': '',
    'CL': 'MCL',
    'ES': 'MES',
    'FDAX': 'FDXS',
    'GBTC': '',
    'GC': 'MGC',
    'HO': '',
    'LE': '',
    'NG': '',
    'NQ': 'MNQ',
    'RTY': 'M2K',
    'SI': '',
    'YM': 'MYM',
    'ZB': '',
    'ZC': '',
    'ZS': ''
}

REGULAR_INSTRUMENTS = [

]

LONG_MAP = {
    '6A': 'Australian Dollar',
    '6A / M6A': 'Australian Dollar & Micros',

    '6B': 'British Pound',
    '6B / M6B': 'British Pound & Micros',

    '6E': 'Australian Dollar Futures',
    '6E / M6E': 'Australian Dollar Futures & Micro',

    '6J': 'Japanese Yen Futures',
    'B': 'Brent Crude Oil Futures',
    'CC': 'Cocoa Futures',

    'CL': 'Crude Oil',
    'CL / MCL': 'Crude Oil & Micros',

    'ES': 'E-Mini S&P 500',
    'ES / MES': 'E-Mini S&P 500 & Micros',

    'FDAX': 'DAX Futures',
    'FDAX / FDXS': 'DAX Futures & Micro',

    'GBTC': 'GrayScale Bitcoin Trust (Bitcoin)',

    'GC': 'Gold Futures',
    'GC / MGC': 'Gold Futures & Micros',

    'HO': 'Heating Oil (NY Harbor ULSD) Futures',
    'LE': 'Live Cattle Futures',
    'NG': 'Henry Hub Natural Gas Futures',

    'NQ': 'E-Mini NASDAQ-100',
    'NQ / MNQ': 'E-Mini NASDAQ-100 & Micros',

    'RTY': 'E-Mini Russell 2000',
    'RTY / M2K': 'E-Mini Russell 2000 & Micros',

    'SI': 'Silver Futures',

    'YM': 'E-Mini Dow',
    'YM / MYM': 'E-Mini Dow & Micros',

    'ZB': 'U.S. Treasury Bond Futures',
    'ZC': 'Corn Futures',
    'ZS': 'Soybean Futures'
}

SKUS_MAP = {
    "Pullback Artist": 123194,
    "Trade Stalker": 123195,
    "Countertrend Majestro": 123196,
    "Golden Parachute": 123197,
    "Low Volatility Rider": 123198,
    "Straight No Chaser": 123199,
    "Eternal Edge": 123200,
    "Break Dancer": 123201,
    "Profit Sniper": 123202,
    "Back From The Future": 123203,
    "Early Birdie": 123204,
    "After Party": 123205,
    "Average Joe Cool": 123206,
    "Breakout Unicorn": 123207,
    "Tech Titan": 123208,
    "Brunch Ranger": 123209,
    "Spike": 123210,
    "Steady Eddy": 123211,
    "Equalizer": 123212,
    "Chaos Theory": 123213,
    "Sleeper Cell": 123214,
    "Meme Squeezer": 123215,
    "Wild Catter": 123216,
    "Mother Gusher": 123217,
    "Sigmund Freud": 123218,
    "Iron Man": 123219,
    "Natural Einstein": 123220,
    "Energizer Bunny": 123221,
    "Black Gold Squeezer": 123231,
    "Firestorm": 123233,
    "Knife Catcher": 123229,
    "El Dorado": 123232,
    "Mother Nature's Hedge": 123234,
    "Petrol Prophet": 123235,
    "Mood Swinger": 123236,
    "Mr. Universe": 123237,
    "Gold Dumper": 123239,
    "Full Metal Jacket": 123238,
    "Chocolate Moby Dick": 123230,
    "Doppler Gobbler": 123240,
    "The Bullet Train": 123241,
    "Lazy River": 123242,
    "Running Bull": 123243,
    "Mason Dixon": 123248,
    "E.T.": 123249,
    "Hoover Bubba": 123250,
    "Four Seasons": 123251,
    "Golden Switch": 123252,
    "Standard & Rich's": 123253,
    "The Industrialist": 123254,
    "Feisty Animal Catcher": 123255,
    "Decentralizer": 123256,
    "Bitcoin Confide": 123257,
    "Henry Hubber": 123258,
    "Harmonicon": 123262,
    "Liquid Gold": 123263,
    "OO7": 123272,
    "Metal Maniac": 123273,
    "Silver Lining": 123274,
    "Season Sucker": 123275,
    "Gold Finger": 123276,
    "Volume Spiker": 123277,
    "Little Guys Revenge": 123278,
    "Aggression Referee": 123279,
    "Inventory Auditor": 123280,
    "Cozy Balancer": 123281,
    "ES Arbiter": 123282,
    "Volume Grinder": 123283,
    "Lucky First Mouse": 123284,
    "Small Bet Hustler": 123285,
    "Euro Hedger": 123286,
    "Aussi Hedger": 123287,
    "Uncle Sam's Bookie": 123288,
    "Currency Coach": 123289,
    "CL Low Risk Retracer": 123290,
    "ES Low Risk Retracer": 123291,
    "NG Low Risk Retracer": 123292,
    "YM Low Risk Retracer": 123293,
    "Open Kimono": 123294,
    "Bandwagon Jumper": 123295,
    "NQ Low Risk Retracer": 123296,
    "High Low Harvester": 123297,
    "Pivot Prince": 123298,
    "Standard Jumper": 123299,
    "Big Bang": 123300,
    "Sleepwalker": 123301,
    "Mr. Brown": 123302,
    "Compositon": 123303,
    "John Smith": 123304,
    "Putzmeister": 123305,
    "Unipeg": 123306,
}

category_map = {
    'Active Robot': 1,
    'Ambitious Robot': 2,
    'Aggressive Robot': 3
}

ROBOT_NORMAL = [
    "After Party",
    "Back From The Future",
    "Bandwagon Jumper",
    "Black Gold Squeezer",
    "Brunch Ranger",
    "Chaos Theory",
    "CL Low Risk Retracer",
    "Early Birdie",
    "El Dorado",
    "Equalizer",
    "ES Low Risk Retracer",
    "Four Seasons",
    "Full Metal Jacket",
    "Golden Switch",
    "Harmonicon",
    "Iron Man",
    "Knife Catcher",
    "Lazy River",
    "Liquid Gold",
    "Low Volatility Rider",
    "Mother Gusher",
    "Mother Nature's Hedge",
    "Mr. Universe",
    "NQ Low Risk Retracer",
    "Open Kimono",
    "Petrol Prophet",
    "Profit Sniper",
    "Sigmund Freud",
    "Sleeper Cell",
    "Standard & Rich's",
    "Steady Eddy",
    "Straight No Chaser",
    "Tech Titan",
    "The Industrialist",
    "Trade Stalker",
    "Wild Catter",
    "YM Low Risk Retracer",
    "Sleepwalker",
    "Compositon",
    "Unipeg",
]

PROS = [
    ["Aggressive Robot", "After Party", "ES / MES"],
    ["Active Robot", "Aggression Referee", "YM / MYM"],
    ["Active Robot", "Aussi Hedger", "6A / M6A"],
    ["Active Robot", "Average Joe Cool", "ES / MES"],
    ["Ambitious Robot", "Back From The Future", "NQ / MNQ"],
    ["Active Robot", "Bandwagon Jumper", "GC"],
    ["Aggressive Robot", "Bitcoin Confide", "GBTC"],
    ["Aggressive Robot", "Black Gold Squeezer", "CL / MCL"],
    ["Active Robot", "Break Dancer", "NQ / MNQ"],
    ["Ambitious Robot", "Breakout Unicorn", "ES / MES"],
    ["Ambitious Robot", "Brunch Ranger", "ES / MES"],
    ["Aggressive Robot", "Chaos Theory", "NQ / MNQ"],
    ["Aggressive Robot", "Chocolate Moby Dick", "CC"],
    ["Active Robot", "CL Low Risk Retracer", "CL"],
    ["Active Robot", "Countertrend Majestro", "ES / MES"],
    ["Active Robot", "Cozy Balancer", "HO"],
    ["Active Robot", "Currency Coach", "6B / M6B"],
    ["Aggressive Robot", "Decentralizer", "GBTC"],
    ["Aggressive Robot", "Doppler Gobbler", "ES / MES"],
    ["Aggressive Robot", "E.T.", "ES / MES"],
    ["Aggressive Robot", "Early Birdie", "NQ / MNQ"],
    ["Aggressive Robot", "El Dorado", "GC / MGC"],
    ["Active Robot", "Energizer Bunny", "NG "],
    ["Aggressive Robot", "Equalizer", "NQ / MNQ"],
    ["Ambitious Robot", "ES Arbiter", "ES / MES"],
    ["Active Robot", "ES Low Risk Retracer", "ES"],
    ["Ambitious Robot", "Eternal Edge", "ES / MES"],
    ["Active Robot", "Euro Hedger", "6E / M6E"],
    ["Aggressive Robot", "Feisty Animal Catcher", "FDAX"],
    ["Ambitious Robot", "Firestorm", "NG "],
    ["Aggressive Robot", "Four Seasons", "ES / MES"],
    ["Ambitious Robot", "Full Metal Jacket", "GC / MGC"],
    ["Aggressive Robot", "Gold Dumper", "GC / MGC"],
    ["Active Robot", "Gold Finger", "GC / MGC"],
    ["Active Robot", "Golden Parachute", "ES / MES"],
    ["Aggressive Robot", "Golden Switch", "GC / MGC"],
    ["Ambitious Robot", "Harmonicon", "ES / MES"],
    ["Ambitious Robot", "Henry Hubber", "NG"],
    ["Aggressive Robot", "High Low Harvester", "ZC"],
    ["Active Robot", "Hoover Bubba", "ES / MES"],
    ["Aggressive Robot", "Inventory Auditor", "CL / MCL"],
    ["Ambitious Robot", "Iron Man", "GC / MGC"],
    ["Ambitious Robot", "Knife Catcher", "CL / MCL"],
    ["Aggressive Robot", "Lazy River", "6E / M6E"],
    ["Active Robot", "Liquid Gold", "CL / MCL"],
    ["Ambitious Robot", "Little Guys Revenge", "RTY / M2K"],
    ["Active Robot", "Low Volatility Rider", "ES / MES"],
    ["Ambitious Robot", "Lucky First Mouse", "NQ / MNQ"],
    ["Ambitious Robot", "Mason Dixon", "ES / MES"],
    ["Aggressive Robot", "Meme Squeezer", "NQ / MNQ"],
    ["Active Robot", "Metal Maniac", "GC / MGC"],
    ["Active Robot", "Mood Swinger", "ES / MES"],
    ["Active Robot", "Mother Gusher", "CL / MCL"],
    ["Ambitious Robot", "Mother Nature's Hedge", "GC / MGC"],
    ["Active Robot", "Mr. Universe", "ES / MES"],
    ["Ambitious Robot", "Natural Einstein", "NG "],
    ["Active Robot", "NG Low Risk Retracer", "NG"],
    ["Active Robot", "NQ Low Risk Retracer", "NQ"],
    ["Active Robot", "OO7", "ZB"],
    ["Active Robot", "Open Kimono", "6J"],
    ["Active Robot", "Petrol Prophet", "CL / MCL"],
    ["Ambitious Robot", "Pivot Prince", "ZS"],
    ["Active Robot", "Profit Sniper", "ES / MES"],
    ["Aggressive Robot", "Pullback Artist", "ES / MES"],
    ["Active Robot", "Running Bull", "LE"],
    ["Aggressive Robot", "Season Sucker", "NQ / MNQ"],
    ["Ambitious Robot", "Sigmund Freud", "GC / MGC"],
    ["Ambitious Robot", "Silver Lining", "SI"],
    ["Active Robot", "Sleeper Cell", "ES / MES"],
    ["Active Robot", "Small Bet Hustler", "YM / MYM"],
    ["Active Robot", "Spike", "ES / MES"],
    ["Aggressive Robot", "Standard & Rich's", "ES / MES"],
    ["Aggressive Robot", "Steady Eddy", "NQ / MNQ"],
    ["Ambitious Robot", "Straight No Chaser", "ES / MES"],
    ["Ambitious Robot", "Tech Titan", "NQ / MNQ"],
    ["Aggressive Robot", "The Bullet Train", "6E / M6E"],
    ["Ambitious Robot", "The Industrialist", "YM / MYM"],
    ["Aggressive Robot", "Trade Stalker", "ES / MES"],
    ["Ambitious Robot", "Uncle Sam's Bookie", "6E / M6E"],
    ["Active Robot", "Volume Grinder", "RTY / M2K"],
    ["Ambitious Robot", "Volume Spiker", "ES / MES"],
    ["Active Robot", "Wild Catter", "CL / MCL"],
    ["Active Robot", "YM Low Risk Retracer", "YM"],
    ["Active Robot", "Mr. Brown", "ES / MES"],
    ["Ambitious Robot", "Standard Jumper", "ES / MES"],
    ["Ambitious Robot", "Big Bang", "NQ / MNQ"],
    ["Ambitious Robot", "Sleepwalker", "NQ / MNQ"],
    ["Aggressive Robot", "Compositon", "NQ / MNQ"],
    ["Aggressive Robot", "John Smith", "NQ / MNQ"],
    ["Aggressive Robot", "Putzmeister", "NQ / MNQ"],
    ["Aggressive Robot", "Unipeg", "NQ / MNQ"],
]

WARCHEST_MODERATE = {
    "Black Gold Squeezer": "MCL",
    "Knife Catcher": "MCL",
    "Liquid Gold": "MCL",
    "Petrol Prophet": "MCL",
    "Wild Catter": "MCL",
    "After Party": "MES",
    "Brunch Ranger": "MES",
    "Harmonicon": "MES",
    "Mr. Universe": "MES",
    "Profit Sniper": "MES",
    "Sleeper Cell": "MES",
    "Standard & Rich's": "MES",
    "Straight No Chaser": "MES",
    "El Dorado": "MGC",
    "Golden Switch": "MGC",
    "Mother Nature's Hedge": "MGC",
    "Sigmund Freud": "MGC",
    "Chaos Theory": "MNQ",
    "Early Birdie": "MNQ",
    "Equalizer": "MNQ",
    # Add Harmonicon MNQ to this portfolio manually
    # "Harmonicon(MNQ)": "MNQ",
    "Steady Eddy": "MNQ",
    "The Industrialist": "MYM",
}

CASHFLOW = {
    "After Party": "MES",
    "Back From The Future": "MNQ",
    "Black Gold Squeezer": "MCL",
    "Brunch Ranger": "MES",
    "Chaos Theory": "MNQ",
    "Early Birdie": "MNQ",
    "El Dorado": "MGC",
    "Equalizer": "NQ",
    "Four Seasons": "MES",
    "Golden Switch": "MGC",
    "Harmonicon": "ES",
    "Henry Hubber": "NG",
    "Knife Catcher": "CL",
    "Liquid Gold": "MCL",
    "Low Volatility Rider": "MES",
    "Mother Nature's Hedge": "MGC",
    "Mr. Universe": "MES",
    "Petrol Prophet": "MCL",
    "Profit Sniper": "ES",
    "Sigmund Freud": "GC",
    "Sleeper Cell": "MES",
    "Standard & Rich's": "MES",
    "Steady Eddy": "MNQ",
    "Straight No Chaser": "MES",
    "Tech Titan": "MNQ",
    "The Industrialist": "MYM",
    "Wild Catter": "MCL"
}

CASHFLOW_AGGRESSIVE = "Cash Flow Aggressive"

CASHFLOW_AGGRESSIVE_BOTS = [
    ["Aggression Referee", 4, "MYM"],
    ["Back From The Future", 2, "MNQ"],
    ["Bandwagon Jumper", 1, "GC"],
    ["Break Dancer", 1, "MNQ"],
    ["Chaos Theory", 1, "MNQ"],
    ["Compositon", 4, "MNQ"],
    ["ES Low Risk Retracer", 1, "ES"],
    ["Golden Switch", 3, "MGC"],
    ["Inventory Auditor", 5, "MCL"],
    ["Low Volatility Rider", 5, "MES"],
    ["Metal Maniac", 3, "MGC"],
    ["Mother Nature's Hedge", 4, "MGC"],
    ["NQ Low Risk Retracer", 1, "NQ"],
    ["Petrol Prophet", 3, "MCL"],
    ["Sleepwalker", 3, "MNQ"],
    ["Standard & Rich's", 1, "MES"],
    ["Steady Eddy", 2, "MNQ"],
    ["Straight No Chaser", 1, "MES"],
    ["Tech Titan", 1, "MNQ"],
    ["The Industrialist", 2, "MYM"],
    ['CL Low Risk Retracer', 1, 'CL']
]

WARCHEST_AGGRESSIVE = 'War Chest Aggressive'

WARCHEST_AGGRESSIVE_BOTS = [
    ["After Party", 1, "MES", ],
    ["Aggression Referee", 2, "MYM", ],
    ["Back From The Future", 1, "MNQ", ],
    ["Bandwagon Jumper", 1, "GC", ],
    ["Break Dancer", 1, "MNQ", ],
    ["Chaos Theory", 1, "MNQ", ],
    ["Compositon", 3, "MNQ", ],
    ["CL Low Risk Retracer", 1, "CL", ],
    ["ES Low Risk Retracer", 1, "ES", ],
    ["Golden Switch", 2, "MGC", ],
    ["Harmonicon", 2, "MES", ],
    ["Inventory Auditor", 3, "MCL", ],
    ["Low Volatility Rider", 3, "MES", ],
    ["Metal Maniac", 2, "MGC", ],
    ["Mother Gusher", 1, "MCL", ],
    ["Mother Nature's Hedge", 2, "MGC", ],
    ["Mr. Universe", 1, "MES", ],
    ["NQ Low Risk Retracer", 1, "NQ", ],
    ["Petrol Prophet", 2, "MCL", ],
    ["Sleepwalker", 2, "MNQ", ],
    ["Standard & Rich's", 1, "MES", ],
    ["Steady Eddy", 1, "MNQ", ],
    ["Straight No Chaser", 1, "MES", ],
    ["Tech Titan", 1, "MNQ", ],
    ["The Industrialist", 2, "MYM", ],
]

MIXED_US_INDEX_FUTURES = "Mixed US Index Futures"

MIXED_US_INDEX_FUTURES_BOTS = [
    ["ES Low Risk Retracer", 1, "ES"],
    ["NQ Low Risk Retracer", 1, "NQ"],
    ["Low Volatility Rider", 3, "MES"],
    ["Standard & Rich's", 2, "MES"],
    ["Compositon", 3, "MNQ"],
    ["The Industrialist", 2, "MYM"],
    ["Tech Titan", 1, "MNQ"],
    ["Sleepwalker", 3, "MNQ"],
    ["Aggression Referee", 4, "MYM"],
    ["Steady Eddy", 2, "MNQ"],
]

DIVERSIFIED = "Diversified"

DIVERSIFIED_BOTS = [
    ["Aggression Referee", 4, "MYM"],
    ["Bandwagon Jumper", 1, "GC"],
    ["CL Low Risk Retracer", 1, "CL"],
    ["Compositon", 3, "MNQ"],
    ["ES Low Risk Retracer", 1, "ES"],
    ["Inventory Auditor", 5, "MCL"],
    ["Iron Man", 2, "MGC"],
    ["Low Volatility Rider", 3, "MES"],
    ["Metal Maniac", 3, "MGC"],
    ["NQ Low Risk Retracer", 1, "NQ"],
    ["Open Kimono", 1, "6J"],
    ["Petrol Prophet", 3, " MCL"],
    ["Sleepwalker", 2, "MNQ"],
    ["Standard & Rich's", 1, "MES"],
    ["Steady Eddy", 1, "MNQ"],
    ["Tech Titan", 1, "MNQ"],
    ["The Industrialist", 2, "MYM"],
]

WARCHEST_CONSERVATIVE = 'War Chest Conservative'

WARCHEST_CONSERVATIVE_BOTS = [
    ["Aggression Referee", 1, "MYM"],
    ["Back From The Future", 1, "MNQ"],
    ["Bandwagon Jumper", 1, "GC"],
    ["Compositon", 2, "MNQ"],
    ["Golden Switch", 1, "MGC"],
    ["Harmonicon", 1, "MES"],
    ["Inventory Auditor", 2, "MCL"],
    ["Low Volatility Rider", 2, "MES"],
    ["Metal Maniac", 2, "MGC"],
    ["NQ Low Risk Retracer", 1, "NQ"],
    ["Petrol Prophet", 1, "MCL"],
    ["Sleepwalker", 1, "MNQ"],
    ["Standard & Rich's", 1, "MES"],
    ["Tech Titan", 1, "MNQ"],
    ["The Industrialist", 1, "MYM"],
    ["Volume Spiker", 1, "MES"],
]

MINI_HEDGE_FUND = "Mini Hedge Fund"
MINI_HEDGE_FUND_BOTS = [
    ["After Party", 5, "MES"],
    ["Aggression Referee", 1, "YM"],
    ["Back From The Future", 2, "MNQ"],
    ["Bandwagon Jumper", 3, "GC"],
    ["Break Dancer", 1, "MNQ"],
    ["Chaos Theory", 2, "MNQ"],
    ["CL Low Risk Retracer", 2, "CL"],
    ["Compositon", 7, "MNQ"],
    ["Early Birdie", 3, "MNQ"],
    ["El Dorado", 2, "MGC"],
    ["Equalizer", 6, "MNQ"],
    ["ES Low Risk Retracer", 2, "ES"],
    ["Golden Switch", 3, "MGC"],
    ["Harmonicon", 4, "MES"],
    ["Inventory Auditor", 1, "CL"],
    ["Iron Man", 2, "MGC"],
    ["Low Volatility Rider", 6, "MES"],
    ["Metal Maniac", 4, "MGC"],
    ["Mother Gusher", 2, "MCL"],
    ["Mother Nature's Hedge", 6, "MGC"],
    ["Mr. Universe", 1, "MES"],
    ["NQ Low Risk Retracer", 2, "NQ"],
    ["Petrol Prophet", 4, "MCL"],
    ["Sleepwalker", 5, "MNQ"],
    ["Standard & Rich's", 3, "MES"],
    ["Steady Eddy", 2, "MNQ"],
    ["Straight No Chaser", 1, "MES"],
    ["Tech Titan", 2, "MNQ"],
    ["The Industrialist", 4, "MYM"],
    ["Trade Stalker", 1, "MES"],
    ["Unipeg", 2, "MNQ"],
    ["Volume Spiker", 4, "MES"],
    ["YM Low Risk Retracer", 1, "YM"],
]
